# Defines a default set of lint rules enforced for projects at Google. For
# details and rationale, see
# https://github.com/dart-lang/pedantic#enabled-lints.

include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.

# Uncomment to specify additional rules.
linter:
 rules:
   # there are some nice lints that were in pedantic that should stay
   - unawaited_futures

analyzer:
 exclude:
   - tool/crawler/mdn
   - tool/webIDL
