targets:
  $default:
    sources:
      exclude: []
    builders:
      build_web_compilers|entrypoint:
        options:
          #compiler: dart2js
          dart2js_args:
            - --fast-startup
            - -O1
            #- --minify
            - --trust-primitives
            #- --dump-info
        release_options:
          dart2js_args:
            - --fast-startup
            - -O4
            - --minify
            - --trust-primitives
            #- --dump-info
