name: js_bindings
description: Complete JS bindings interop with autocomplete and documentation.
version: 0.0.4-dev.5
repository: https://github.com/jodinathan/js_bindings

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  meta: ^1.4.0
  js: ^0.6.4

dev_dependencies:
  archive: ^3.1.2
  dart_style: ^2.0.1
  collection: ^1.15.0
  glob: ^2.0.1
  html: ^0.15.0
  http: ^0.13.3
  lints: ^1.0.0
  recase: ^4.0.0
  tcp_scanner: ^1.1.2
  test: ^1.16.0
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
