name: js_bindings
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  dart_style: ^2.0.1
  meta: ^1.4.0
  html: ^0.15.0
  archive: ^3.1.2
  tcp_scanner: ^1.1.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
