name: js_bindings
description: Complete JS bindings interop with autocomplete and documentation.
version: 0.1.1
repository: https://github.com/jodinathan/js_bindings
sponsor: https://invertase.io

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta: ^1.4.0
  js: ^0.6.4

dev_dependencies:
  archive: ^3.1.2
  dart_style: ^2.0.1
  collection: ^1.15.0
  glob: ^2.0.1
  html: ^0.15.0
  http: ^0.13.3
  lints: ^2.0.0
  recase: ^4.0.0
  tcp_scanner: ^2.0.5
  test: ^1.16.0
  build_runner: ^2.2.1
  build_web_compilers: ^3.2.6
